name: Go
on: [push]
jobs:

  test:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - uses: actions/checkout@v2

    - name: install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.31.0
        golangci-lint run

    - name: test
      run: |
        go test -race -cover -coverprofile=coverage.txt
        go run ./lib/utils/check-cov

