name: Go
on: [push]
jobs:

  test:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - uses: actions/checkout@v2

    - name: setup
      run: (cd && GO111MODULE=on go get github.com/ysmood/kit/cmd/godev)

    - run: godev -l -r -m 100
