name: Test

on: [push, pull_request]

env:
  GODEBUG: tracebackancestors=1000

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - uses: actions/checkout@v2

    - name: lint
      run: go get github.com/ysmood/golangci-lint && golangci-lint

    - name: test
      env:
        TERM: xterm-256color
      run: go test -race -coverprofile=coverage.out ./... && go run ./cmd/check-cov
